### ISSUE TITLE
Make use of new collections api

### ISSUE THREAD

**Issue by seanrcollings** [atomicjolt/atomic-libs#15]
React Aria released a new collections API package: https://github.com/adobe/react-spectrum/tree/main/packages/%40react-aria/collections

This package should in theory let us resolve some of the long standing issues with collections components 

## Components

- [x] CustomSelect
- [x] ListBox
- [x] Menu
- [x] IconMenu
- [x] ComboBox
- [x] Tabs
- [x] atomicjolt/atomic-libs#9
- [x] atomicjolt/atomic-libs#10
- [x] atomicjolt/atomic-libs#11

**Comment by seanrcollings** [comment]
The tabs issue has since been resolved
